/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:ae201cb1-58c9-447f-8b20-a8529db1cc54",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_gXCcgiIck",
  aws_user_pools_web_client_id: "1uakb79fa9vqo3io2pdruerjjp",
  oauth: {},
};

export default awsmobile;
